// <auto-generated />
using System;
using AIStock.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIStock.Infrastructure.Migrations
{
    [DbContext(typeof(AIStockDbContext))]
    [Migration("20260531053004_AddSelectionTables")]
    partial class AddSelectionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.AgentMemoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_time_ms");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("input");

                    b.Property<string>("KeyMetrics")
                        .HasColumnType("longtext")
                        .HasColumnName("key_metrics");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("output");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stock_code");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("success");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_type");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("AgentId", "StockCode", "CreatedAt");

                    b.ToTable("agent_memory");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.CompanyChainRelationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChainId")
                        .HasColumnType("bigint")
                        .HasColumnName("chain_id");

                    b.Property<string>("ChainNode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("chain_node");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("company_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("CompanyCode", "ChainId")
                        .IsUnique();

                    b.ToTable("company_chain_relation");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.CompanyRelationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("relation_type");

                    b.Property<string>("SourceCompany")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source_company");

                    b.Property<string>("TargetCompany")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("target_company");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("SourceCompany");

                    b.HasIndex("TargetCompany");

                    b.HasIndex("SourceCompany", "TargetCompany", "RelationType")
                        .IsUnique();

                    b.ToTable("company_relation");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.DailyMarketSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amplitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amplitude");

                    b.Property<decimal>("ChangePercent")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("change_percent");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("close");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<bool>("IsLimitUp")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_limit_up");

                    b.Property<decimal>("Ma10")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ma10");

                    b.Property<decimal>("Ma20")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ma20");

                    b.Property<decimal>("Ma5")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ma5");

                    b.Property<decimal>("MacdDea")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("macd_dea");

                    b.Property<decimal>("MacdDif")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("macd_dif");

                    b.Property<bool>("MacdGoldenCross")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("macd_golden_cross");

                    b.Property<decimal>("MainNetInflow")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("main_net_inflow");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("PeTtm")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pe_ttm");

                    b.Property<decimal>("Rise20d")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("rise20d");

                    b.Property<decimal>("Rsi")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("rsi");

                    b.Property<decimal>("TotalMarketCap")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_market_cap");

                    b.Property<decimal>("TurnoverRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("turnover_rate");

                    b.Property<decimal>("VolumeRatio")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("volume_ratio");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Code", "Date")
                        .IsUnique();

                    b.ToTable("daily_market_snapshot");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.DragonTigerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BuyAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("buy_amount");

                    b.Property<string>("BuySeatsJson")
                        .HasColumnType("text")
                        .HasColumnName("buy_seats_json");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<bool>("HasInstitution")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_institution");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("NetBuyAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("net_buy_amount");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("reason");

                    b.Property<decimal>("SellAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("sell_amount");

                    b.Property<string>("SellSeatsJson")
                        .HasColumnType("text")
                        .HasColumnName("sell_seats_json");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Code", "Date")
                        .IsUnique();

                    b.ToTable("dragon_tiger");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.EventConceptRelationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConceptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("concept_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.HasKey("Id");

                    b.HasIndex("ConceptName");

                    b.HasIndex("EventId", "ConceptName")
                        .IsUnique();

                    b.ToTable("event_concept_relation");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.EventRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("Credibility")
                        .HasColumnType("int")
                        .HasColumnName("credibility");

                    b.Property<DateTime?>("EventTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("event_type");

                    b.Property<int?>("Importance")
                        .HasColumnType("int")
                        .HasColumnName("importance");

                    b.Property<string>("LLMAnalysis")
                        .HasColumnType("longtext")
                        .HasColumnName("llm_analysis");

                    b.Property<string>("RelatedConcepts")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("related_concepts");

                    b.Property<string>("RelatedStocks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("related_stocks");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sentiment");

                    b.Property<decimal?>("SentimentScore")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("sentiment_score");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventTime");

                    b.HasIndex("EventType");

                    b.ToTable("event_record");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.EventStockRelationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stock_code");

                    b.HasKey("Id");

                    b.HasIndex("StockCode");

                    b.HasIndex("EventId", "StockCode")
                        .IsUnique();

                    b.ToTable("event_stock_relation");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.GraphCandidateEdgeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Credibility")
                        .HasColumnType("int")
                        .HasColumnName("credibility");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("edge_type");

                    b.Property<string>("FromEntity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("from_entity");

                    b.Property<string>("LastSourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("last_source_url");

                    b.Property<int>("MentionCount")
                        .HasColumnType("int")
                        .HasColumnName("mention_count");

                    b.Property<bool>("Promoted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("promoted");

                    b.Property<string>("ToEntity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("to_entity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EdgeType");

                    b.HasIndex("FromEntity", "ToEntity", "EdgeType")
                        .IsUnique();

                    b.ToTable("graph_candidate_edge");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.IndustryChainEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("chain_name");

                    b.Property<string>("ChildNode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("child_node");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("NodeType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_type");

                    b.Property<string>("ParentNode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("parent_node");

                    b.HasKey("Id");

                    b.HasIndex("ChainName");

                    b.HasIndex("ChainName", "ParentNode", "ChildNode");

                    b.ToTable("industry_chain");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.KlineDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("ChangePercent")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("change_percent");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("close");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datetime");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("high");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("interval");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("open");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.Property<decimal?>("TurnoverRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("turnover_rate");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("DateTime");

                    b.HasIndex("Code", "DateTime", "Interval")
                        .IsUnique();

                    b.ToTable("kline_data");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.LLMModelConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("int")
                        .HasColumnName("max_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("temperature");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("llm_model_config");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.PositionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BuyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("buy_time");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("cost_price");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("current_price");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("profit");

                    b.Property<decimal>("ProfitRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("profit_rate");

                    b.Property<long>("SellableVolume")
                        .HasColumnType("bigint")
                        .HasColumnName("sellable_volume");

                    b.Property<string>("StrategyName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("strategy_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("position");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.PromptTemplateEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("version");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("int")
                        .HasColumnName("max_tokens");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("longtext")
                        .HasColumnName("system_prompt");

                    b.Property<double>("Temperature")
                        .HasColumnType("double")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_prompt");

                    b.Property<string>("Variables")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("variables");

                    b.HasKey("Name", "Version");

                    b.HasIndex("Category");

                    b.ToTable("prompt_template");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.StockBaseEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int")
                        .HasColumnName("employee_count");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsDelisted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_delisted");

                    b.Property<DateTime?>("ListDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("list_date");

                    b.Property<string>("MainBusiness")
                        .HasColumnType("text")
                        .HasColumnName("main_business");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("market");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Profile")
                        .HasColumnType("text")
                        .HasColumnName("profile");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("province");

                    b.Property<decimal?>("RegCapital")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("reg_capital");

                    b.Property<string>("SubIndustry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sub_industry");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("website");

                    b.HasKey("Code");

                    b.HasIndex("Industry");

                    b.HasIndex("Market");

                    b.ToTable("stock_base");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.StockConceptRelationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ConceptId")
                        .HasColumnType("int")
                        .HasColumnName("concept_id");

                    b.Property<string>("ConceptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("concept_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("QuoteCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("quote_code");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stock_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConceptName");

                    b.HasIndex("StockCode", "ConceptName")
                        .IsUnique();

                    b.ToTable("stock_concept_relation");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.TradeRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgreeId")
                        .HasColumnType("bigint")
                        .HasColumnName("agree_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("commission");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("direction");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<string>("SignalId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("signal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("status_message");

                    b.Property<string>("StrategyName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("strategy_name");

                    b.Property<DateTime?>("TradeTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("trade_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.ToTable("trade_record");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.EventConceptRelationEntity", b =>
                {
                    b.HasOne("AIStock.Infrastructure.Database.Entities.EventRecordEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("AIStock.Infrastructure.Database.Entities.EventStockRelationEntity", b =>
                {
                    b.HasOne("AIStock.Infrastructure.Database.Entities.EventRecordEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });
#pragma warning restore 612, 618
        }
    }
}
