<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="HtmlAgilityPack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIStock.Core\AIStock.Core.csproj" />
    <ProjectReference Include="..\AIStock.Infrastructure\AIStock.Infrastructure.csproj" />
    <ProjectReference Include="..\AIStock.LLM\AIStock.LLM.csproj" />
  </ItemGroup>

</Project>
