<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIStock.Core\AIStock.Core.csproj" />
    <ProjectReference Include="..\AIStock.Data\AIStock.Data.csproj" />
    <ProjectReference Include="..\AIStock.Infrastructure\AIStock.Infrastructure.csproj" />
  </ItemGroup>

</Project>
